title: WIngforce
theme: minima
author: Abel Tung
email: abeltung@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Here is where I will post the new thing I am writing.
 It is about life love, war, and less.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
